before_script:
  - unset RAILS_ENV
  - unset RACK_ENV
branches: master
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
language: ruby
matrix:
  include:
    - gemfile: Gemfile
      rvm: 2.0.0
      env: COVERAGE=1
rvm:
  - 1.9.3
  - 2.0.0
script: rspec
