before_script:
  - unset RAILS_ENV
  - unset RACK_ENV
branches:
  only:
    - master
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - gemfile: Gemfile
      rvm: 2.0.0
      env: COVERAGE=1
rvm:
  - 1.9.3
  - 2.0.0
  - "2.1"
  - ruby-head
script: bundle exec rspec
